### PR TITLE
Issue48/tile size

### LINKED ISSUE #48: Tile size
screen shot 2018-05-23 at 12 20 04 pm
* Bottom margin is too long
* Top margin between FCC Meetups and top is too long
* Size of the tile is rather large, especially on mobile
* Height of tile is an issue, too big

Note: Could use a redesign, it's a good first attempt but wasn't fully realized. We should improve this version before we iterate on v2 or if we even want a v2.

### PR DESCRIPTION
**Pull request by klcantrell**
Slimmed down the tile by 1) consolidating the "meetup status" parts of the tile's template logic - now, the button says "Join Us" if there's an upcoming meetup and "You Just Missed It!" if it has passed, and 2) tweaking on styles.

See pics below and let me know what edits need made before this would go through.

## Before

tiles-before

## After

tiles-after

Closes #48 .

### CODE REVIEW

**Comment by klcantrell** [comment]
issue48/tile-size code review changes:  …
* ditched scroll bars for expand/contract feature
* ditched rounded corners
* more room between text content and buttons

**Comment by mattattaq** [comment]
My vote is to stack them at 885px, that'd be an easy update.

**Comment by klcantrell** [comment]
Awesome, I'll make the update  - should tighten it up.  Plus, if more cards ever get added we can always go in and change the layout to suit more cards.

**Comment by klcantrell** [comment]
Done!  Made the breakpoint 900px because even at 885px it still bunched up if you went slowly enough.

**Comment by mattattaq** [comment]
Looks good to me!

**Pull request merged**
